name: Makefile CI

on:
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: echo vars
      run:  echo ${{ vars.GBIF_USERNAME }} ${{ vars.GBIF_EMAIL }}

    - name: Make GBIF download
      env:
        GBIF_USERNAME: ${{ vars.GBIF_USERNAME }}
        GBIF_PASSWORD: ${{ secrets.GBIF_PASSWORD }}
        GBIF_EMAIL: ${{ vars.GBIF_EMAIL }}
      run: make data/downloadquery_id.txt

    - name: Download images
      run: make data/images.zip

    - name: Build heatmap chart
      run: make data/heatmap.png

    - name: Make bibtex
      env:
        GBIF_USERNAME: ${{ vars.GBIF_USERNAME }}
        GBIF_PASSWORD: ${{ secrets.GBIF_PASSWORD }}
        GBIF_EMAIL: ${{ vars.GBIF_EMAIL }}
      run: make data/gbif_download.bib

    - name: Attach built artifact (images.zip) to run 
      if: ${{ github.event_name == 'workflow_dispatch'}}
      uses: actions/upload-artifact@v4
      with:
        name: images.zip
        path: data/images.zip

    - name: Attach built artifact (families.csv) to run 
      if: ${{ github.event_name == 'workflow_dispatch'}}
      uses: actions/upload-artifact@v4
      with:
        name: families.csv
        path: data/families.csv

    - name: Attach built artifact (gbif_download.bib) to run 
      if: ${{ github.event_name == 'workflow_dispatch'}}
      uses: actions/upload-artifact@v4
      with:
        name: gbif_download.bib
        path: data/gbif_download.bib

    - name: Attach built artifact (heatmap.png) to run 
      if: ${{ github.event_name == 'workflow_dispatch'}}
      uses: actions/upload-artifact@v4
      with:
        name: heatmap.png
        path: data/heatmap.png        